### ISSUE TITLE
Attempted to access a missing method

### ISSUE THREAD

**Issue by SanBest93** [ezhevita/GameRemover#67]
win10 pc, chrome.
i installed it for the firs time: "...\ASF-win-x64\plugins\GameRemover-generic\GameRemover.dll"
i entered the command in asf web-interface: deletegame BotName 250957
asf said:

> [12:53:59]<BotName > Unknown command!

log said:

> 2023-07-19 12:53:59|ArchiSteamFarm-31396|ERROR|ASF|OnBotCommand() System.MissingMethodException: Attempted to access a missing method.
>    at GameRemover.GameRemoverPlugin.ResponseDeleteGame(Bot bot, EAccess access, String appIDsText)
>    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine&)
>    at GameRemover.GameRemoverPlugin.ResponseDeleteGame(Bot bot, EAccess access, String appIDsText)
>    at GameRemover.GameRemoverPlugin.<>c__DisplayClass7_0.<ResponseDeleteGame>b__1(Bot bot)
>    at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
>    at System.Threading.Tasks.Task.WhenAll[TResult](IEnumerable`1)
>    at ArchiSteamFarm.Core.Utilities.InParallel[T](IEnumerable`1 tasks)
>    at GameRemover.GameRemoverPlugin.ResponseDeleteGame(UInt64 steamID, EAccess access, String botNames, String appIDsText)
>    at ArchiSteamFarm.Core.Utilities.InParallel[T](IEnumerable`1 tasks)
>    at ArchiSteamFarm.Plugins.PluginsCore.OnBotCommand(Bot bot, EAccess access, String message, String[] args, UInt64 steamID)

**Comment by ezhevita** [comment]
Fixed in v2.3.0
